### ISSUE TITLE
Autoscroll also scrolls horizontally in the messages area.

### ISSUE THREAD

**Issue by Void-025** [programmer-pony/BD-AutoScroll#2]
It doesn't actually go far enough to hide any messages, but it causes everything to "wiggle" unless you moved your mouse in a perfectly straight line.

Maybe it could be possible to add a setting to restrict scrolling to only vertical?

**Comment by hackermare** [comment]
Can't replicate. What theme are you using? Does it happen on all chats?

**Comment by Void-025** [comment]
I'm using [this theme](https://github.com/fluffingtons/revert-discord), but after checking some other servers... It looks like it only happens on two servers, out of ~10 checked, which is extremely strange. I also can't really think of any commonalities between the two servers (I thought it might have something to do with permissions as I'm the owner of one of those servers, but on the other one I have no special permissions, and creating another server doesn't cause the issue).

**Comment by hackermare** [comment]
Sorry for the delay. I implemented the setting that you mentioned in the latest release. Let me know if you find any more issues.
