### ISSUE TITLE
Paste when middle clicking

### ISSUE THREAD

**Issue by DarkXoa** [programmer-pony/BD-AutoScroll#7]
When Discord is not the active window, middle clicking on the window will paste the most recently highlighted text, not the most recent item from the clipboard.

Desired outcome: middle clicking on the Discord window should never paste anything. Middle clicking on an inactive window should only ever activate autoscrolling

**Comment by hackermare** [comment]
That's just how X11 and Wayland work. You can try to disable middle click pasting from your desktop environment or use something like [XMousePasteBlock](https://github.com/milaq/XMousePasteBlock).
